/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Customer { 'contact' : string, 'name' : string }
export interface LineItem {
  'serviceItem' : ServiceItem,
  'total' : bigint,
  'quantity' : bigint,
}
export interface Payment {
  'id' : bigint,
  'method' : PaymentMethod,
  'date' : Time,
  'notes' : string,
  'amount' : bigint,
}
export type PaymentMethod = { 'other' : string } |
  { 'card' : null } |
  { 'cash' : null } |
  { 'bankTransfer' : null };
export interface Receipt {
  'id' : bigint,
  'status' : ReceiptStatus,
  'total' : bigint,
  'balance' : bigint,
  'payments' : Array<Payment>,
  'customer' : Customer,
  'date' : Time,
  'number' : string,
  'items' : Array<LineItem>,
}
export type ReceiptStatus = { 'open' : null } |
  { 'paid' : null } |
  { 'partial' : null };
export interface ServiceItem { 'name' : string, 'price' : bigint }
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[Customer], undefined>,
  'addPayment' : ActorMethod<[bigint, Payment], undefined>,
  'addServiceItem' : ActorMethod<[ServiceItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReceipt' : ActorMethod<
    [string, Customer, Array<LineItem>, bigint],
    bigint
  >,
  'getBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getReceiptPayments' : ActorMethod<[bigint], Array<Payment>>,
  'getReceipts' : ActorMethod<[], Array<Receipt>>,
  'getReceiptsSorted' : ActorMethod<[string], Array<Receipt>>,
  'getServiceItems' : ActorMethod<[], Array<ServiceItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];