/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Customer = IDL.Record({ 'contact' : IDL.Text, 'name' : IDL.Text });
export const PaymentMethod = IDL.Variant({
  'other' : IDL.Text,
  'card' : IDL.Null,
  'cash' : IDL.Null,
  'bankTransfer' : IDL.Null,
});
export const Time = IDL.Int;
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'method' : PaymentMethod,
  'date' : Time,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ServiceItem = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LineItem = IDL.Record({
  'serviceItem' : ServiceItem,
  'total' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const BusinessProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ReceiptStatus = IDL.Variant({
  'open' : IDL.Null,
  'paid' : IDL.Null,
  'partial' : IDL.Null,
});
export const Receipt = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReceiptStatus,
  'total' : IDL.Nat,
  'balance' : IDL.Nat,
  'payments' : IDL.Vec(Payment),
  'customer' : Customer,
  'date' : Time,
  'number' : IDL.Text,
  'items' : IDL.Vec(LineItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([Customer], [], []),
  'addPayment' : IDL.Func([IDL.Nat, Payment], [], []),
  'addServiceItem' : IDL.Func([ServiceItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReceipt' : IDL.Func(
      [IDL.Text, Customer, IDL.Vec(LineItem), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getReceiptPayments' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'getReceipts' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
  'getReceiptsSorted' : IDL.Func([IDL.Text], [IDL.Vec(Receipt)], ['query']),
  'getServiceItems' : IDL.Func([], [IDL.Vec(ServiceItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Customer = IDL.Record({ 'contact' : IDL.Text, 'name' : IDL.Text });
  const PaymentMethod = IDL.Variant({
    'other' : IDL.Text,
    'card' : IDL.Null,
    'cash' : IDL.Null,
    'bankTransfer' : IDL.Null,
  });
  const Time = IDL.Int;
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'method' : PaymentMethod,
    'date' : Time,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ServiceItem = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LineItem = IDL.Record({
    'serviceItem' : ServiceItem,
    'total' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const BusinessProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ReceiptStatus = IDL.Variant({
    'open' : IDL.Null,
    'paid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const Receipt = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReceiptStatus,
    'total' : IDL.Nat,
    'balance' : IDL.Nat,
    'payments' : IDL.Vec(Payment),
    'customer' : Customer,
    'date' : Time,
    'number' : IDL.Text,
    'items' : IDL.Vec(LineItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([Customer], [], []),
    'addPayment' : IDL.Func([IDL.Nat, Payment], [], []),
    'addServiceItem' : IDL.Func([ServiceItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReceipt' : IDL.Func(
        [IDL.Text, Customer, IDL.Vec(LineItem), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getReceiptPayments' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
    'getReceipts' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
    'getReceiptsSorted' : IDL.Func([IDL.Text], [IDL.Vec(Receipt)], ['query']),
    'getServiceItems' : IDL.Func([], [IDL.Vec(ServiceItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };