/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Receipt {
    id: bigint;
    status: ReceiptStatus;
    total: bigint;
    balance: bigint;
    payments: Array<Payment>;
    customer: Customer;
    date: Time;
    number: string;
    items: Array<LineItem>;
}
export type Time = bigint;
export interface LineItem {
    serviceItem: ServiceItem;
    total: bigint;
    quantity: bigint;
}
export type PaymentMethod = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "card";
    card: null;
} | {
    __kind__: "cash";
    cash: null;
} | {
    __kind__: "bankTransfer";
    bankTransfer: null;
};
export interface ServiceItem {
    name: string;
    price: bigint;
}
export interface Payment {
    id: bigint;
    method: PaymentMethod;
    date: Time;
    notes: string;
    amount: bigint;
}
export interface BusinessProfile {
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface Customer {
    contact: string;
    name: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum ReceiptStatus {
    open = "open",
    paid = "paid",
    partial = "partial"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomer(customer: Customer): Promise<void>;
    addPayment(receiptId: bigint, payment: Payment): Promise<void>;
    addServiceItem(item: ServiceItem): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createReceipt(number: string, customer: Customer, items: Array<LineItem>, total: bigint): Promise<bigint>;
    getBusinessProfile(): Promise<BusinessProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomers(): Promise<Array<Customer>>;
    getReceiptPayments(receiptId: bigint): Promise<Array<Payment>>;
    getReceipts(): Promise<Array<Receipt>>;
    getReceiptsSorted(sortBy: string): Promise<Array<Receipt>>;
    getServiceItems(): Promise<Array<ServiceItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveBusinessProfile(profile: BusinessProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { BusinessProfile as _BusinessProfile, Customer as _Customer, LineItem as _LineItem, Payment as _Payment, PaymentMethod as _PaymentMethod, Receipt as _Receipt, ReceiptStatus as _ReceiptStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async addPayment(arg0: bigint, arg1: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0, to_candid_Payment_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0, to_candid_Payment_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addServiceItem(arg0: ServiceItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceItem(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createReceipt(arg0: string, arg1: Customer, arg2: Array<LineItem>, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReceipt(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReceipt(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getBusinessProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getReceiptPayments(arg0: bigint): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceiptPayments(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceiptPayments(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceipts(): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceipts();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceipts();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceiptsSorted(arg0: string): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceiptsSorted(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceiptsSorted(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceItems(): Promise<Array<ServiceItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceItems();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveBusinessProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBusinessProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBusinessProfile(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_PaymentMethod_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ReceiptStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReceiptStatus): ReceiptStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Receipt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Receipt): Receipt {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    method: _PaymentMethod;
    date: _Time;
    notes: string;
    amount: bigint;
}): {
    id: bigint;
    method: PaymentMethod;
    date: Time;
    notes: string;
    amount: bigint;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n14(_uploadFile, _downloadFile, value.method),
        date: value.date,
        notes: value.notes,
        amount: value.amount
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReceiptStatus;
    total: bigint;
    balance: bigint;
    payments: Array<_Payment>;
    customer: _Customer;
    date: _Time;
    number: string;
    items: Array<_LineItem>;
}): {
    id: bigint;
    status: ReceiptStatus;
    total: bigint;
    balance: bigint;
    payments: Array<Payment>;
    customer: Customer;
    date: Time;
    number: string;
    items: Array<LineItem>;
} {
    return {
        id: value.id,
        status: from_candid_ReceiptStatus_n19(_uploadFile, _downloadFile, value.status),
        total: value.total,
        balance: value.balance,
        payments: from_candid_vec_n11(_uploadFile, _downloadFile, value.payments),
        customer: value.customer,
        date: value.date,
        number: value.number,
        items: value.items
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    card: null;
} | {
    cash: null;
} | {
    bankTransfer: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "card";
    card: null;
} | {
    __kind__: "cash";
    cash: null;
} | {
    __kind__: "bankTransfer";
    bankTransfer: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "card" in value ? {
        __kind__: "card",
        card: value.card
    } : "cash" in value ? {
        __kind__: "cash",
        cash: value.cash
    } : "bankTransfer" in value ? {
        __kind__: "bankTransfer",
        bankTransfer: value.bankTransfer
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    open: null;
} | {
    paid: null;
} | {
    partial: null;
}): ReceiptStatus {
    return "open" in value ? ReceiptStatus.open : "paid" in value ? ReceiptStatus.paid : "partial" in value ? ReceiptStatus.partial : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Receipt>): Array<Receipt> {
    return value.map((x)=>from_candid_Receipt_n17(_uploadFile, _downloadFile, x));
}
function to_candid_PaymentMethod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Payment_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payment): _Payment {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    method: PaymentMethod;
    date: Time;
    notes: string;
    amount: bigint;
}): {
    id: bigint;
    method: _PaymentMethod;
    date: _Time;
    notes: string;
    amount: bigint;
} {
    return {
        id: value.id,
        method: to_candid_PaymentMethod_n3(_uploadFile, _downloadFile, value.method),
        date: value.date,
        notes: value.notes,
        amount: value.amount
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "card";
    card: null;
} | {
    __kind__: "cash";
    cash: null;
} | {
    __kind__: "bankTransfer";
    bankTransfer: null;
}): {
    other: string;
} | {
    card: null;
} | {
    cash: null;
} | {
    bankTransfer: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "card" ? {
        card: value.card
    } : value.__kind__ === "cash" ? {
        cash: value.cash
    } : value.__kind__ === "bankTransfer" ? {
        bankTransfer: value.bankTransfer
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
